var searchData=
[
  ['target_500',['Target',['../classtensorflow_1_1serving_1_1Target.html',1,'tensorflow::serving']]],
  ['target_3c_20std_3a_3aunique_5fptr_3c_20loader_20_3e_20_3e_501',['Target&lt; std::unique_ptr&lt; Loader &gt; &gt;',['../classtensorflow_1_1serving_1_1Target.html',1,'tensorflow::serving']]],
  ['targetbase_502',['TargetBase',['../classtensorflow_1_1serving_1_1TargetBase.html',1,'tensorflow::serving']]],
  ['targetbase_3c_20inputtype_20_3e_503',['TargetBase&lt; InputType &gt;',['../classtensorflow_1_1serving_1_1TargetBase.html',1,'tensorflow::serving']]],
  ['targetbase_3c_20std_3a_3aunique_5fptr_3c_20loader_20_3e_20_3e_504',['TargetBase&lt; std::unique_ptr&lt; Loader &gt; &gt;',['../classtensorflow_1_1serving_1_1TargetBase.html',1,'tensorflow::serving']]],
  ['targetbase_3c_20storagepath_20_3e_505',['TargetBase&lt; StoragePath &gt;',['../classtensorflow_1_1serving_1_1TargetBase.html',1,'tensorflow::serving']]],
  ['tensorflowclassificationserviceimpl_506',['TensorflowClassificationServiceImpl',['../classtensorflow_1_1serving_1_1TensorflowClassificationServiceImpl.html',1,'tensorflow::serving']]],
  ['tensorflowfileprobingenv_507',['TensorflowFileProbingEnv',['../classtensorflow_1_1serving_1_1TensorflowFileProbingEnv.html',1,'tensorflow::serving']]],
  ['tensorflowmultiinferencerunner_508',['TensorFlowMultiInferenceRunner',['../classtensorflow_1_1serving_1_1TensorFlowMultiInferenceRunner.html',1,'tensorflow::serving']]],
  ['tensorflowpredictor_509',['TensorflowPredictor',['../classtensorflow_1_1serving_1_1TensorflowPredictor.html',1,'tensorflow::serving']]],
  ['tensorflowregressionserviceimpl_510',['TensorflowRegressionServiceImpl',['../classtensorflow_1_1serving_1_1TensorflowRegressionServiceImpl.html',1,'tensorflow::serving']]],
  ['tensorflowservingfunctionregistration_511',['TensorflowServingFunctionRegistration',['../classtensorflow_1_1serving_1_1init_1_1TensorflowServingFunctionRegistration.html',1,'tensorflow::serving::init']]],
  ['tensorsignature_512',['TensorSignature',['../structtensorflow_1_1serving_1_1TensorSignature.html',1,'tensorflow::serving']]],
  ['testclientrequest_513',['TestClientRequest',['../structtensorflow_1_1serving_1_1net__http_1_1TestClientRequest.html',1,'tensorflow::serving::net_http']]],
  ['testclientresponse_514',['TestClientResponse',['../structtensorflow_1_1serving_1_1net__http_1_1TestClientResponse.html',1,'tensorflow::serving::net_http']]],
  ['testevhttpconnection_515',['TestEvHTTPConnection',['../classtensorflow_1_1serving_1_1net__http_1_1TestEvHTTPConnection.html',1,'tensorflow::serving::net_http']]],
  ['testhttpclientinterface_516',['TestHTTPClientInterface',['../classtensorflow_1_1serving_1_1net__http_1_1TestHTTPClientInterface.html',1,'tensorflow::serving::net_http']]],
  ['tf_5fjpeg_5ferror_5fmgr_517',['tf_jpeg_error_mgr',['../structtf__jpeg__error__mgr.html',1,'']]],
  ['tflitebatchtask_518',['TfLiteBatchTask',['../classtensorflow_1_1serving_1_1TfLiteBatchTask.html',1,'tensorflow::serving']]],
  ['tfliteinterpreterpool_519',['TfLiteInterpreterPool',['../classtensorflow_1_1serving_1_1internal_1_1TfLiteInterpreterPool.html',1,'tensorflow::serving::internal']]],
  ['tfliteinterpreterwrapper_520',['TfLiteInterpreterWrapper',['../classtensorflow_1_1serving_1_1internal_1_1TfLiteInterpreterWrapper.html',1,'tensorflow::serving::internal']]],
  ['tflitesession_521',['TfLiteSession',['../classtensorflow_1_1serving_1_1TfLiteSession.html',1,'tensorflow::serving']]],
  ['tfrtclassificationserviceimpl_522',['TFRTClassificationServiceImpl',['../classtensorflow_1_1serving_1_1TFRTClassificationServiceImpl.html',1,'tensorflow::serving']]],
  ['tfrtgetmodelmetadataimpl_523',['TFRTGetModelMetadataImpl',['../classtensorflow_1_1serving_1_1TFRTGetModelMetadataImpl.html',1,'tensorflow::serving']]],
  ['tfrthttprestapihandler_524',['TFRTHttpRestApiHandler',['../classtensorflow_1_1serving_1_1TFRTHttpRestApiHandler.html',1,'tensorflow::serving']]],
  ['tfrtpredictionserviceimpl_525',['TfrtPredictionServiceImpl',['../classtensorflow_1_1serving_1_1TfrtPredictionServiceImpl.html',1,'tensorflow::serving']]],
  ['tfrtregressionserviceimpl_526',['TFRTRegressionServiceImpl',['../classtensorflow_1_1serving_1_1TFRTRegressionServiceImpl.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelfactory_527',['TfrtSavedModelFactory',['../classtensorflow_1_1serving_1_1TfrtSavedModelFactory.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelfactoryregistry_528',['TfrtSavedModelFactoryRegistry',['../classtensorflow_1_1serving_1_1TfrtSavedModelFactoryRegistry.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelservable_529',['TfrtSavedModelServable',['../classtensorflow_1_1serving_1_1TfrtSavedModelServable.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelsourceadapter_530',['TfrtSavedModelSourceAdapter',['../classtensorflow_1_1serving_1_1TfrtSavedModelSourceAdapter.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelsourceadaptercreator_531',['TfrtSavedModelSourceAdapterCreator',['../classtensorflow_1_1serving_1_1TfrtSavedModelSourceAdapterCreator.html',1,'tensorflow::serving']]],
  ['threadpoolexecutor_532',['ThreadPoolExecutor',['../classtensorflow_1_1serving_1_1ThreadPoolExecutor.html',1,'tensorflow::serving']]],
  ['threadpoolfactory_533',['ThreadPoolFactory',['../classtensorflow_1_1serving_1_1ThreadPoolFactory.html',1,'tensorflow::serving']]],
  ['threadsafestatus_534',['ThreadSafeStatus',['../classtensorflow_1_1serving_1_1ThreadSafeStatus.html',1,'tensorflow::serving']]]
];
