var searchData=
[
  ['savedmodelbatchingtask_445',['SavedModelBatchingTask',['../structtensorflow_1_1serving_1_1SavedModelBatchingTask.html',1,'tensorflow::serving']]],
  ['savedmodelbundlefactory_446',['SavedModelBundleFactory',['../classtensorflow_1_1serving_1_1SavedModelBundleFactory.html',1,'tensorflow::serving']]],
  ['savedmodelbundlesourceadapter_447',['SavedModelBundleSourceAdapter',['../classtensorflow_1_1serving_1_1SavedModelBundleSourceAdapter.html',1,'tensorflow::serving']]],
  ['savedmodelbundlesourceadaptercreator_448',['SavedModelBundleSourceAdapterCreator',['../classtensorflow_1_1serving_1_1SavedModelBundleSourceAdapterCreator.html',1,'tensorflow::serving']]],
  ['scopedthreadpools_449',['ScopedThreadPools',['../classtensorflow_1_1serving_1_1ScopedThreadPools.html',1,'tensorflow::serving']]],
  ['servable_450',['Servable',['../classtensorflow_1_1serving_1_1Servable.html',1,'tensorflow::serving']]],
  ['servableaction_451',['ServableAction',['../structtensorflow_1_1serving_1_1AspiredVersionPolicy_1_1ServableAction.html',1,'tensorflow::serving::AspiredVersionPolicy']]],
  ['servabledata_452',['ServableData',['../classtensorflow_1_1serving_1_1ServableData.html',1,'tensorflow::serving']]],
  ['servablehandle_453',['ServableHandle',['../classtensorflow_1_1serving_1_1ServableHandle.html',1,'tensorflow::serving']]],
  ['servableid_454',['ServableId',['../structtensorflow_1_1serving_1_1ServableId.html',1,'tensorflow::serving']]],
  ['servablerequest_455',['ServableRequest',['../structtensorflow_1_1serving_1_1ServableRequest.html',1,'tensorflow::serving']]],
  ['servablestate_456',['ServableState',['../structtensorflow_1_1serving_1_1ServableState.html',1,'tensorflow::serving']]],
  ['servablestateandtime_457',['ServableStateAndTime',['../structtensorflow_1_1serving_1_1ServableStateMonitor_1_1ServableStateAndTime.html',1,'tensorflow::serving::ServableStateMonitor']]],
  ['servablestatemonitor_458',['ServableStateMonitor',['../classtensorflow_1_1serving_1_1ServableStateMonitor.html',1,'tensorflow::serving']]],
  ['servablestatesnapshot_459',['ServableStateSnapshot',['../structtensorflow_1_1serving_1_1ServableStateSnapshot.html',1,'tensorflow::serving']]],
  ['server_460',['Server',['../classtensorflow_1_1serving_1_1main_1_1Server.html',1,'tensorflow::serving::main']]],
  ['servercore_461',['ServerCore',['../classtensorflow_1_1serving_1_1ServerCore.html',1,'tensorflow::serving']]],
  ['servercoretest_462',['ServerCoreTest',['../classtensorflow_1_1serving_1_1test__util_1_1ServerCoreTest.html',1,'tensorflow::serving::test_util']]],
  ['servercoretestaccess_463',['ServerCoreTestAccess',['../classtensorflow_1_1serving_1_1test__util_1_1ServerCoreTestAccess.html',1,'tensorflow::serving::test_util']]],
  ['serveroptions_464',['ServerOptions',['../classtensorflow_1_1serving_1_1net__http_1_1ServerOptions.html',1,'tensorflow::serving::net_http']]],
  ['serverrequestinterface_465',['ServerRequestInterface',['../classtensorflow_1_1serving_1_1net__http_1_1ServerRequestInterface.html',1,'tensorflow::serving::net_http']]],
  ['serverrequestlogger_466',['ServerRequestLogger',['../classtensorflow_1_1serving_1_1ServerRequestLogger.html',1,'tensorflow::serving']]],
  ['serversupport_467',['ServerSupport',['../classtensorflow_1_1serving_1_1net__http_1_1ServerSupport.html',1,'tensorflow::serving::net_http']]],
  ['servingclient_468',['ServingClient',['../classServingClient.html',1,'']]],
  ['servingsession_469',['ServingSession',['../classtensorflow_1_1serving_1_1ServingSession.html',1,'tensorflow::serving']]],
  ['servingsessionwrapper_470',['ServingSessionWrapper',['../classtensorflow_1_1serving_1_1ServingSessionWrapper.html',1,'tensorflow::serving']]],
  ['sessionbundle_471',['SessionBundle',['../structtensorflow_1_1serving_1_1SessionBundle.html',1,'tensorflow::serving']]],
  ['sessionwrapperignorethreadpooloptions_472',['SessionWrapperIgnoreThreadPoolOptions',['../classtensorflow_1_1serving_1_1SessionWrapperIgnoreThreadPoolOptions.html',1,'tensorflow::serving']]],
  ['shardedreadptrs_473',['ShardedReadPtrs',['../classtensorflow_1_1serving_1_1internal__read__ptr__holder_1_1ShardedReadPtrs.html',1,'tensorflow::serving::internal_read_ptr_holder']]],
  ['shardedreadptrs_3c_20handlesmap_20_3e_474',['ShardedReadPtrs&lt; HandlesMap &gt;',['../classtensorflow_1_1serving_1_1internal__read__ptr__holder_1_1ShardedReadPtrs.html',1,'tensorflow::serving::internal_read_ptr_holder']]],
  ['shardedreadptrs_3c_20stringtorequestloggersmap_20_3e_475',['ShardedReadPtrs&lt; StringToRequestLoggersMap &gt;',['../classtensorflow_1_1serving_1_1internal__read__ptr__holder_1_1ShardedReadPtrs.html',1,'tensorflow::serving::internal_read_ptr_holder']]],
  ['shareableownedptr_476',['ShareableOwnedPtr',['../classtensorflow_1_1serving_1_1FastReadDynamicPtr_1_1ShareableOwnedPtr.html',1,'tensorflow::serving::FastReadDynamicPtr']]],
  ['sharedptrhandle_477',['SharedPtrHandle',['../classtensorflow_1_1serving_1_1SharedPtrHandle.html',1,'tensorflow::serving']]],
  ['signaturewithbatchingsessionschedulercreator_478',['SignatureWithBatchingSessionSchedulerCreator',['../structtensorflow_1_1serving_1_1SignatureWithBatchingSessionSchedulerCreator.html',1,'tensorflow::serving']]],
  ['simpleloader_479',['SimpleLoader',['../classtensorflow_1_1serving_1_1SimpleLoader.html',1,'tensorflow::serving']]],
  ['simpleloadersourceadapter_480',['SimpleLoaderSourceAdapter',['../classtensorflow_1_1serving_1_1SimpleLoaderSourceAdapter.html',1,'tensorflow::serving']]],
  ['simpleloadersourceadapter_3c_20storagepath_2c_20std_3a_3aunordered_5fmap_3c_20string_2c_20string_20_3e_20_3e_481',['SimpleLoaderSourceAdapter&lt; StoragePath, std::unordered_map&lt; string, string &gt; &gt;',['../classtensorflow_1_1serving_1_1SimpleLoaderSourceAdapter.html',1,'tensorflow::serving']]],
  ['simpleloadersourceadapter_3c_20storagepath_2c_20string_20_3e_482',['SimpleLoaderSourceAdapter&lt; StoragePath, string &gt;',['../classtensorflow_1_1serving_1_1SimpleLoaderSourceAdapter.html',1,'tensorflow::serving']]],
  ['singlereadptr_483',['SingleReadPtr',['../classtensorflow_1_1serving_1_1internal__read__ptr__holder_1_1SingleReadPtr.html',1,'tensorflow::serving::internal_read_ptr_holder']]],
  ['singlerequestpredictstreamedcontext_484',['SingleRequestPredictStreamedContext',['../classtensorflow_1_1serving_1_1SingleRequestPredictStreamedContext.html',1,'tensorflow::serving']]],
  ['singletaskscheduler_485',['SingleTaskScheduler',['../classtensorflow_1_1serving_1_1internal_1_1SingleTaskScheduler.html',1,'tensorflow::serving::internal']]],
  ['source_486',['Source',['../classtensorflow_1_1serving_1_1Source.html',1,'tensorflow::serving']]],
  ['source_3c_20outputtype_20_3e_487',['Source&lt; OutputType &gt;',['../classtensorflow_1_1serving_1_1Source.html',1,'tensorflow::serving']]],
  ['source_3c_20storagepath_20_3e_488',['Source&lt; StoragePath &gt;',['../classtensorflow_1_1serving_1_1Source.html',1,'tensorflow::serving']]],
  ['sourceadapter_489',['SourceAdapter',['../classtensorflow_1_1serving_1_1SourceAdapter.html',1,'tensorflow::serving']]],
  ['sourceadapter_3c_20t_2c_20t_20_3e_490',['SourceAdapter&lt; T, T &gt;',['../classtensorflow_1_1serving_1_1SourceAdapter.html',1,'tensorflow::serving']]],
  ['sourcerouter_491',['SourceRouter',['../classtensorflow_1_1serving_1_1SourceRouter.html',1,'tensorflow::serving']]],
  ['staticmanagerbuilder_492',['StaticManagerBuilder',['../classtensorflow_1_1serving_1_1StaticManagerBuilder.html',1,'tensorflow::serving']]],
  ['staticsourcerouter_493',['StaticSourceRouter',['../classtensorflow_1_1serving_1_1StaticSourceRouter.html',1,'tensorflow::serving']]],
  ['staticstoragepathsource_494',['StaticStoragePathSource',['../classtensorflow_1_1serving_1_1StaticStoragePathSource.html',1,'tensorflow::serving']]],
  ['storagepatherrorinjectingsourceadaptercreator_495',['StoragePathErrorInjectingSourceAdapterCreator',['../classtensorflow_1_1serving_1_1test__util_1_1StoragePathErrorInjectingSourceAdapterCreator.html',1,'tensorflow::serving::test_util']]],
  ['streamingbatchscheduler_496',['StreamingBatchScheduler',['../classtensorflow_1_1serving_1_1StreamingBatchScheduler.html',1,'tensorflow::serving']]],
  ['streamlogger_497',['StreamLogger',['../classtensorflow_1_1serving_1_1StreamLogger.html',1,'tensorflow::serving']]],
  ['streamlogger_3c_20predictrequest_2c_20predictresponse_20_3e_498',['StreamLogger&lt; PredictRequest, PredictResponse &gt;',['../classtensorflow_1_1serving_1_1StreamLogger.html',1,'tensorflow::serving']]],
  ['subscription_499',['Subscription',['../classtensorflow_1_1serving_1_1EventBus_1_1Subscription.html',1,'tensorflow::serving::EventBus']]]
];
