var searchData=
[
  ['target_272',['Target',['../classtensorflow_1_1serving_1_1Target.html',1,'tensorflow::serving']]],
  ['target_3c_20std_3a_3aunique_5fptr_3c_20loader_20_3e_20_3e_273',['Target&lt; std::unique_ptr&lt; Loader &gt; &gt;',['../classtensorflow_1_1serving_1_1Target.html',1,'tensorflow::serving']]],
  ['targetbase_274',['TargetBase',['../classtensorflow_1_1serving_1_1TargetBase.html',1,'tensorflow::serving']]],
  ['targetbase_3c_20inputtype_20_3e_275',['TargetBase&lt; InputType &gt;',['../classtensorflow_1_1serving_1_1TargetBase.html',1,'tensorflow::serving']]],
  ['targetbase_3c_20std_3a_3aunique_5fptr_3c_20loader_20_3e_20_3e_276',['TargetBase&lt; std::unique_ptr&lt; Loader &gt; &gt;',['../classtensorflow_1_1serving_1_1TargetBase.html',1,'tensorflow::serving']]],
  ['targetbase_3c_20storagepath_20_3e_277',['TargetBase&lt; StoragePath &gt;',['../classtensorflow_1_1serving_1_1TargetBase.html',1,'tensorflow::serving']]],
  ['tensorflowclassificationserviceimpl_278',['TensorflowClassificationServiceImpl',['../classtensorflow_1_1serving_1_1TensorflowClassificationServiceImpl.html',1,'tensorflow::serving']]],
  ['tensorflowfileprobingenv_279',['TensorflowFileProbingEnv',['../classtensorflow_1_1serving_1_1TensorflowFileProbingEnv.html',1,'tensorflow::serving']]],
  ['tensorflowmultiinferencerunner_280',['TensorFlowMultiInferenceRunner',['../classtensorflow_1_1serving_1_1TensorFlowMultiInferenceRunner.html',1,'tensorflow::serving']]],
  ['tensorflowpredictor_281',['TensorflowPredictor',['../classtensorflow_1_1serving_1_1TensorflowPredictor.html',1,'tensorflow::serving']]],
  ['tensorflowregressionserviceimpl_282',['TensorflowRegressionServiceImpl',['../classtensorflow_1_1serving_1_1TensorflowRegressionServiceImpl.html',1,'tensorflow::serving']]],
  ['tensorflowservingfunctionregistration_283',['TensorflowServingFunctionRegistration',['../classtensorflow_1_1serving_1_1init_1_1TensorflowServingFunctionRegistration.html',1,'tensorflow::serving::init']]],
  ['tensorsignature_284',['TensorSignature',['../structtensorflow_1_1serving_1_1TensorSignature.html',1,'tensorflow::serving']]],
  ['testclientrequest_285',['TestClientRequest',['../structtensorflow_1_1serving_1_1net__http_1_1TestClientRequest.html',1,'tensorflow::serving::net_http']]],
  ['testclientresponse_286',['TestClientResponse',['../structtensorflow_1_1serving_1_1net__http_1_1TestClientResponse.html',1,'tensorflow::serving::net_http']]],
  ['testevhttpconnection_287',['TestEvHTTPConnection',['../classtensorflow_1_1serving_1_1net__http_1_1TestEvHTTPConnection.html',1,'tensorflow::serving::net_http']]],
  ['testhttpclientinterface_288',['TestHTTPClientInterface',['../classtensorflow_1_1serving_1_1net__http_1_1TestHTTPClientInterface.html',1,'tensorflow::serving::net_http']]],
  ['tf_5fjpeg_5ferror_5fmgr_289',['tf_jpeg_error_mgr',['../structtf__jpeg__error__mgr.html',1,'']]],
  ['tflitebatchtask_290',['TfLiteBatchTask',['../classtensorflow_1_1serving_1_1TfLiteBatchTask.html',1,'tensorflow::serving']]],
  ['tfliteinterpreterpool_291',['TfLiteInterpreterPool',['../classtensorflow_1_1serving_1_1internal_1_1TfLiteInterpreterPool.html',1,'tensorflow::serving::internal']]],
  ['tfliteinterpreterwrapper_292',['TfLiteInterpreterWrapper',['../classtensorflow_1_1serving_1_1internal_1_1TfLiteInterpreterWrapper.html',1,'tensorflow::serving::internal']]],
  ['tflitesession_293',['TfLiteSession',['../classtensorflow_1_1serving_1_1TfLiteSession.html',1,'tensorflow::serving']]],
  ['tfrtclassificationserviceimpl_294',['TFRTClassificationServiceImpl',['../classtensorflow_1_1serving_1_1TFRTClassificationServiceImpl.html',1,'tensorflow::serving']]],
  ['tfrtgetmodelmetadataimpl_295',['TFRTGetModelMetadataImpl',['../classtensorflow_1_1serving_1_1TFRTGetModelMetadataImpl.html',1,'tensorflow::serving']]],
  ['tfrthttprestapihandler_296',['TFRTHttpRestApiHandler',['../classtensorflow_1_1serving_1_1TFRTHttpRestApiHandler.html',1,'tensorflow::serving']]],
  ['tfrtpredictionserviceimpl_297',['TfrtPredictionServiceImpl',['../classtensorflow_1_1serving_1_1TfrtPredictionServiceImpl.html',1,'tensorflow::serving']]],
  ['tfrtregressionserviceimpl_298',['TFRTRegressionServiceImpl',['../classtensorflow_1_1serving_1_1TFRTRegressionServiceImpl.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelfactory_299',['TfrtSavedModelFactory',['../classtensorflow_1_1serving_1_1TfrtSavedModelFactory.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelfactoryregistry_300',['TfrtSavedModelFactoryRegistry',['../classtensorflow_1_1serving_1_1TfrtSavedModelFactoryRegistry.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelservable_301',['TfrtSavedModelServable',['../classtensorflow_1_1serving_1_1TfrtSavedModelServable.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelsourceadapter_302',['TfrtSavedModelSourceAdapter',['../classtensorflow_1_1serving_1_1TfrtSavedModelSourceAdapter.html',1,'tensorflow::serving']]],
  ['tfrtsavedmodelsourceadaptercreator_303',['TfrtSavedModelSourceAdapterCreator',['../classtensorflow_1_1serving_1_1TfrtSavedModelSourceAdapterCreator.html',1,'tensorflow::serving']]],
  ['threadpoolexecutor_304',['ThreadPoolExecutor',['../classtensorflow_1_1serving_1_1ThreadPoolExecutor.html',1,'tensorflow::serving']]],
  ['threadpoolfactory_305',['ThreadPoolFactory',['../classtensorflow_1_1serving_1_1ThreadPoolFactory.html',1,'tensorflow::serving']]],
  ['threadsafestatus_306',['ThreadSafeStatus',['../classtensorflow_1_1serving_1_1ThreadSafeStatus.html',1,'tensorflow::serving']]]
];
